apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-chat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: code-chat
  template:
    metadata:
      labels:
        app: code-chat
    spec:
      containers:
        - name: code-chat
          image: overstackescola/code-chat:latest
          ports:
            - containerPort: 8101
          env:
            - name: SERVER_PORT
              value: "8101"

            - name: SESSION_HTTP_SECRET
              value: "W0NvZGVDaGF0XTpbU2Vzc"

            - name: LOG_LEVEL
              value: "ERROR|WARN|INFO|DEBUG|LOG"

            - name: LOG_COLOR
              value: "true"

            - name: DATABASE_URL
              value: "postgres://codechat:140414Kaio@codechat.postgres.database.azure.com:5432/codechatv2"

            - name: DATABASE_SYNC_MESSAGES
              value: "true"

            - name: DATABASE_SAVE_DATA_NEW_MESSAGE
              value: "true"

            - name: DATABASE_SAVE_MESSAGE_UPDATE
              value: "true"

            - name: DATABASE_SAVE_DATA_CONTACTS
              value: "true"

            - name: DATABASE_SAVE_DATA_CHATS
              value: "true"

            - name: DATABASE_SAVE_LOGS
              value: "true"

            - name: DATABASE_SAVE_ACTIVITY_LOGS
              value: "true"

            - name: WEBHOOK_GLOBAL_URL
              value: "https://webhookv4.picchat.io/webhook/codechat"

            - name: WEBHOOK_GLOBAL_ENABLED
              value: "true"

            - name: INSTANCE_EXPIRATION_TIME
              value: "false"

            - name: CONFIG_SESSION_PHONE_CLIENT
              value: "Picchat"

            - name: CONFIG_SESSION_PHONE_NAME
              value: "Edge"

            - name: WA_VERSION
              value: "[ 2, 3000, 1015901307 ]"

            - name: QRCODE_LIMIT
              value: "30"

            - name: QRCODE_EXPIRATION_TIME
              value: "20"

            - name: QRCODE_LIGHT_COLOR
              value: "#ffffff"

            - name: QRCODE_DARK_COLOR
              value: "#000000"

            - name: CONNECTION_TIMEOUT
              value: "300"

            - name: AUTHENTICATION_GLOBAL_AUTH_TOKEN
              value: "zYzP7ocstxh3Sscefew4FZTCu4ehnM8v4hu"

            - name: AUTHENTICATION_JWT_EXPIRES_IN
              value: "0"

            - name: AUTHENTICATION_JWT_SECRET
              value: "3RFYwe-fwf4fw4w8e-BrLZzx"

            - name: PROVIDER_ENABLED
              value: "false"

            - name: PROVIDER_HOST
              value: "127.0.0.1"

            - name: PROVIDER_PORT
              value: "5656"

            - name: PROVIDER_PREFIX
              value: "codechat"

            - name: API_BACKEND
              value: ""

            - name: S3_ENABLED
              value: "false"

            - name: S3_ACCESS_KEY
              value: "access_key_id"

            - name: S3_SECRET_KEY
              value: "secret_access_key"

            - name: S3_BUCKET
              value: "bucket_name"

            - name: S3_PORT
              value: "9000"

            - name: S3_ENDPOINT
              value: "127.0.0.1"

            - name: S3_USE_SSL
              value: "false"

      imagePullSecrets:
        - name: my-dockerhub-secret
---
apiVersion: v1
kind: Service
metadata:
  name: code-chat-service
spec:
  ports:
    - port: 8101
  selector:
    app: code-chat
  type: ClusterIP